name: Fabric Deploy (Dev → Prod)

on:
  workflow_dispatch:
    inputs:
      items_json:
        description: 'Optional JSON array for selective deploy (items)'
        required: false
        default: ''
      note:
        description: 'Deployment note'
        required: false
        default: 'Automated deploy'
  push:
    branches: [ "main" ]
    paths:
      - "fabric/**"
      - "ops/**"
      - ".github/workflows/fabric-deploy.yml"

concurrency:
  group: fabric-prod-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: windows-latest
    environment: prod     # uses env-scoped secrets/vars + approvals
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy Dev → Prod (skip Warehouses by default)
        shell: pwsh
        env:
          FABRIC_TENANT_ID:      ${{ secrets.FABRIC_TENANT_ID }}
          FABRIC_CLIENT_ID:      ${{ secrets.FABRIC_CLIENT_ID }}
          FABRIC_CLIENT_SECRET:  ${{ secrets.FABRIC_CLIENT_SECRET }}
          FABRIC_PIPELINE_NAME:  ${{ vars.FABRIC_PIPELINE_NAME }}
          FABRIC_SOURCE_STAGE:   ${{ vars.FABRIC_SOURCE_STAGE || 'Development' }}
          FABRIC_TARGET_STAGE:   ${{ vars.FABRIC_TARGET_STAGE || 'Production' }}
          INPUT_NOTE:            ${{ github.event.inputs.note }}
          INPUT_ITEMS_JSON:      ${{ github.event.inputs.items_json }}
        run: |
          ./ops/Deploy-Fabric.ps1 `
            -TenantId        $env:FABRIC_TENANT_ID `
            -ClientId        $env:FABRIC_CLIENT_ID `
            -ClientSecret    $env:FABRIC_CLIENT_SECRET `
            -PipelineName    $env:FABRIC_PIPELINE_NAME `
            -SourceStage     $env:FABRIC_SOURCE_STAGE `
            -TargetStage     $env:FABRIC_TARGET_STAGE `
            -Note            ($env:INPUT_NOTE ? $env:INPUT_NOTE : "Automated deploy") `
            -ItemsJson       ($env:INPUT_ITEMS_JSON ? $env:INPUT_ITEMS_JSON : "")
